name = "cf-video"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
SERVER_NAME = "CF-Video"
SERVER_VERSION = "0.1.0"
TMDB_API_BASE = "https://api.themoviedb.org/3"

[[d1_databases]]
binding = "DB"
database_name = "cf-video-metadata"
database_id = "75a3cab0-4819-4e44-b0c6-b3df3ba26b56"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cf-video"
